apiVersion: "v1"
kind: "PersistentVolume"
metadata:
  name: data-volume-SIZEg-INST
spec:
  capacity:
    storage: SIZEGi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: fast
  hostPath:
    path: /data/volumeINST
  #gcePersistentDisk:
  #  fsType: xfs
  #  pdName: pd-ssd-disk-SIZEg-INST

